syntax = "proto3";

package vod.api;

import "base.proto";

option cc_generic_services = true;

message UploadFileRequest {
  string directory = 1;
  string original_name = 2;
  bytes content = 3;
  RequestContext context = 4;
  string mime_type = 5;
  string bundle_id = 6;
  string role = 7;
}

message UploadFileResponse {
  bool success = 1;
  string message = 2;
  FileInfo file = 3;
  RpcStatus status = 4;
}

message DownloadFileRequest {
  string public_url = 1;
  RequestContext context = 2;
}

message DownloadFileResponse {
  bool success = 1;
  string message = 2;
  bytes content = 3;
  string content_type = 4;
  RpcStatus status = 5;
}

message RemoveFileRequest { string file_id = 1; }
message RemoveFileResponse { bool success = 1; string message = 2; }

service FileService {
  rpc RemoveFile(RemoveFileRequest) returns (RemoveFileResponse);
  rpc UploadFile(UploadFileRequest) returns (UploadFileResponse);
  rpc DownloadFile(DownloadFileRequest) returns (DownloadFileResponse);
}
